version: '3'
services:
  digidom_spoznawanje:
     image: digidom_spoznawanje:latest
     restart: always
     privileged: true
     environment:
       PORTAUDIO_SOUND_CARD_NAME: "ReSpeaker 4 Mic Array (UAC1.0)"
       VOICE_ACTIVITY_DETECTION_ALGO: "usb"
