version: '3'
services:
  digidom_spoznawanje:
     image: digidom_spoznawanje:latest
     restart: always
     privileged: true
     environment:
       PORTAUDIO_SOUND_CARD_NAME: "ac108"
       VOICE_ACTIVITY_DETECTION_ALGO: "rtc"
